version: '3'
services:
  front:
    build: ./front
    container_name: api_sale_service_front
    volumes:
      - ./front:/app
      - api_sale_service_front_node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  api_sale_service_front_node_modules:
