version: '3'
services:
  front:
    build: ./front
    container_name: api_sale_service_front
    volumes:
      - ./front:/front
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm run dev
  api:
    build: ./api
    container_name: api_sale_service_api
    volumes:
      - ./api:/api
    ports:
      - 80:8000
    stdin_open: true
    tty: true
    command: chalice local --host=0.0.0.0 --port=8000

