version: '3'
services:
  front:
    build: ./front
    container_name: api_sale_service_front
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    command: npm run dev

